name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - run: pip install -r requirements_test.txt
      - run: pytest tests/ --cov=custom_components/paddle_conditions --cov-report=xml -v
