name: HACS Validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: hacs/action@main
        with:
          category: integration
